services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - VITE_API_URL=http://localhost:3001/v1.0
    depends_on:
      - backend

  backend:
    build:
      context: ./mock_graph_api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./mock_graph_api/src:/app/src